// <auto-generated />
using System;
using CarPilot.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CarPilot.Server.Data.Migrations
{
    [DbContext(typeof(CarPilotDbContext))]
    [Migration("20260824044839_InitialGarage")]
    partial class InitialGarage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarPilot.Server.Entities.ConversationEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MessagesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelatedRecordIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SharedWith")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("UserId", "VehicleId");

                    b.ToTable("conversations", (string)null);
                });

            modelBuilder.Entity("CarPilot.Server.Entities.DocumentChunkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.Property<Vector>("Embedding")
                        .IsRequired()
                        .HasColumnType("vector(384)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UserId", "DocumentId");

                    b.ToTable("document_chunks", (string)null);
                });

            modelBuilder.Entity("CarPilot.Server.Entities.MaintenanceRecordEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("numeric");

                    b.Property<string>("Date")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int?>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Shop")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("UserId", "VehicleId");

                    b.ToTable("maintenance_records", (string)null);
                });

            modelBuilder.Entity("CarPilot.Server.Entities.UserProfileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarBucket")
                        .HasColumnType("text");

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("CarPilot.Server.Entities.VehicleDocumentEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaintenanceRecordId")
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long?>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StorageBucket")
                        .HasColumnType("text");

                    b.Property<string>("StorageKey")
                        .HasColumnType("text");

                    b.Property<string>("UploadedAt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("VehicleId")
                        .IsRequired()
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("MaintenanceRecordId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("UserId", "VehicleId");

                    b.ToTable("vehicle_documents", (string)null);
                });

            modelBuilder.Entity("CarPilot.Server.Entities.VehicleEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("EstimatedValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinanceAmountFinanced")
                        .HasColumnType("numeric");

                    b.Property<int?>("FinanceAnnualMileageAllowance")
                        .HasColumnType("integer");

                    b.Property<decimal?>("FinanceApr")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinanceDownPayment")
                        .HasColumnType("numeric");

                    b.Property<string>("FinanceKind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinanceLender")
                        .HasColumnType("text");

                    b.Property<decimal?>("FinanceMonthlyPayment")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinancePayoffAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("FinanceResidualValue")
                        .HasColumnType("numeric");

                    b.Property<string>("FinanceStartDate")
                        .HasColumnType("text");

                    b.Property<int?>("FinanceTermMonths")
                        .HasColumnType("integer");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceAgentName")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceAgentPhone")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceCoverageType")
                        .HasColumnType("text");

                    b.Property<decimal?>("InsuranceDeductible")
                        .HasColumnType("numeric");

                    b.Property<string>("InsuranceEffectiveDate")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceInsurer")
                        .HasColumnType("text");

                    b.Property<decimal?>("InsuranceMonthlyPremium")
                        .HasColumnType("numeric");

                    b.Property<string>("InsurancePolicyNumber")
                        .HasColumnType("text");

                    b.Property<string>("InsuranceRenewalDate")
                        .HasColumnType("text");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Trim")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Vin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WarrantyContractNumber")
                        .HasColumnType("text");

                    b.Property<string>("WarrantyCoverageLevel")
                        .HasColumnType("text");

                    b.Property<decimal?>("WarrantyDeductible")
                        .HasColumnType("numeric");

                    b.Property<string>("WarrantyExpirationDate")
                        .HasColumnType("text");

                    b.Property<int?>("WarrantyExpirationMileage")
                        .HasColumnType("integer");

                    b.Property<string>("WarrantyNotes")
                        .HasColumnType("text");

                    b.Property<string>("WarrantyPlanName")
                        .HasColumnType("text");

                    b.Property<decimal?>("WarrantyPricePaid")
                        .HasColumnType("numeric");

                    b.Property<string>("WarrantyProvider")
                        .HasColumnType("text");

                    b.Property<string>("WarrantyStartDate")
                        .HasColumnType("text");

                    b.Property<int?>("WarrantyStartMileage")
                        .HasColumnType("integer");

                    b.Property<bool?>("WarrantyTransferable")
                        .HasColumnType("boolean");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("vehicles", (string)null);
                });

            modelBuilder.Entity("CarPilot.Server.Entities.ConversationEntity", b =>
                {
                    b.HasOne("CarPilot.Server.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Conversations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.DocumentChunkEntity", b =>
                {
                    b.HasOne("CarPilot.Server.Entities.VehicleDocumentEntity", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.MaintenanceRecordEntity", b =>
                {
                    b.HasOne("CarPilot.Server.Entities.VehicleEntity", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.VehicleDocumentEntity", b =>
                {
                    b.HasOne("CarPilot.Server.Entities.MaintenanceRecordEntity", "MaintenanceRecord")
                        .WithMany("Documents")
                        .HasForeignKey("MaintenanceRecordId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarPilot.Server.Entities.VehicleEntity", "Vehicle")
                        .WithMany("Documents")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaintenanceRecord");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.VehicleEntity", b =>
                {
                    b.HasOne("CarPilot.Server.Entities.UserProfileEntity", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.MaintenanceRecordEntity", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.UserProfileEntity", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.VehicleDocumentEntity", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("CarPilot.Server.Entities.VehicleEntity", b =>
                {
                    b.Navigation("Conversations");

                    b.Navigation("Documents");

                    b.Navigation("MaintenanceRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
